apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-job
  namespace: orcamentos-app
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  backoffLimit: 2
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "orcamentos-api-role"
        vault.hashicorp.com/agent-inject-secret-config: "secret/data/orcamentos-api"
        vault.hashicorp.com/agent-inject-template-config: |
          {{- with secret "secret/data/orcamentos-api" -}}
          {{- range $key, $value := .Data.data }}
          export {{ $key }}="{{ $value }}"
          {{- end }}
          {{- end }}
        vault.hashicorp.com/agent-pre-populate-only: "true"
    spec:
      restartPolicy: Never
      containers:
        - name: migrate-job
          image: registry.gitlab.com/bruninho51/projeto-controle-gastos:v1.14.0
          imagePullPolicy: Always
          command:
            - sh
            - -c
            - |
              . /vault/secrets/config
              npx prisma migrate deploy
      imagePullSecrets:
        - name: gitlab-registry-secret
