apiVersion: apps/v1
kind: Deployment
metadata:
  name: orcamentos-api-deployment
  namespace: orcamentos-app
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: orcamentos-api
  template:
    metadata:
      labels:
        app: orcamentos-api
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "orcamentos-api-role"
        vault.hashicorp.com/agent-inject-secret-config: |
          secret/data/orcamentos-api
          secret/data/jwt
        vault.hashicorp.com/agent-inject-template-config: |
          {{- with secret "secret/data/orcamentos-api" -}}
          {{- range $k, $v := .Data.data }}
          export {{ $k }}="{{ $v }}"
          {{- end }}
          {{- end }}
          {{- with secret "secret/data/jwt" -}}
          {{- range $k, $v := .Data.data }}
          export {{ $k }}="{{ $v }}"
          {{- end }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-firebase-cert.json: "secret/data/firebase-cert"
        vault.hashicorp.com/agent-inject-template-firebase-cert.json: |
          {{- with secret "secret/data/firebase-cert" -}}
          {{ .Data.data.content }}
          {{- end }}
    spec:
      containers:
        - name: orcamentos-api
          image: registry.gitlab.com/bruninho51/projeto-controle-gastos:v1.18.2
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: gitlab-registry-secret
